server:
   port: 9191

spring:
   h2:
      console:
         enabled: true
   application:
      name: PAYMENT-SERVICE
logging:
#   level: info
   file: 
      name: E:/eclipse_workspaces/microservice-prep/jt-services.log

# moved to jt-config-properties
# eureka:
#    client:
#       register-with-eureka: true
#       fetch-registry: true
#       service-url:
#          default-zone: http://localhost:8761/eureka
#    instance: localhost   

